In [1]:
import numpy as np

In [2]:
n = 3
bruh = [[0 for _ in range(6*n - 2)] for _ in range (n**2 + 1)]

for r in range(n):
    for c in range(n):
        # Calculate the conditions that it will cover
        row_map = r # will be 0->n-1
        col_map = (n) + c # will be n->2n-1
        pos_diag_map = (2*n) + r + c # will be 2n->4n-2
        neg_diag_map = (4*n - 2) + n - c + r # will be 4n-2->6n-3

        # Populate the cover_mat. 1 row for each possible position
        bruh[r*n+c+1][row_map] = 1 
        bruh[r*n+c+1][col_map] = 1 
        bruh[r*n+c+1][pos_diag_map] = 1 
        bruh[r*n+c+1][neg_diag_map] = 1 

for i in range(len(bruh)):
    print(bruh[i])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0]
[1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]
[1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0]
[0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0]
[0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0]
[0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0]
[0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1]
[0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0]
[0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]


In [3]:
# N-Queens
from DLX import DLX_solver

bruh = DLX_solver("N-Queens", 5, [], None)

bruh.empty_to_exact_cover()
bruh.exact_cover_to_dancing_list()
bruh.AlgoX()

print(len(bruh.solutions))

10


In [4]:
# Sudoku
sudoku = np.array([
                    [0,2,0, 0,0,6, 9,0,0],
                    [0,0,0, 0,5,0, 0,2,0],
                    [6,0,0, 3,0,0, 0,0,0],

                    [9,4,0, 0,0,7, 0,0,0],
                    [0,0,0, 4,0,0, 7,0,0],
                    [0,3,0, 2,0,0, 0,8,0],

                    [0,0,9, 0,4,0, 0,0,0],
                    [3,0,0, 9,0,2, 0,1,7],
                    [0,0,8, 0,0,0, 0,0,2]
    ])

from DLX import DLX_solver

dlx = DLX_solver("Sudoku", None, [], sudoku)
dlx.exact_cover_to_dancing_list()
dlx.AlgoX()

[[4 2 5 8 1 6 9 7 3]
 [8 9 3 7 5 4 6 2 1]
 [6 1 7 3 2 9 5 4 8]
 [9 4 1 6 8 7 2 3 5]
 [5 8 2 4 3 1 7 6 9]
 [7 3 6 2 9 5 1 8 4]
 [2 7 9 1 4 8 3 5 6]
 [3 5 4 9 6 2 8 1 7]
 [1 6 8 5 7 3 4 9 2]]
