# Exact-Cover via Dancing Links: N-Queens & Sudoku Demos
## Abstract
We explore Knuth’s Algorithm X using a toroidal Dancing-Links (DLX) implementation to solve two canonical exact-cover problems: the N-Queens puzzle and Sudoku. First, we show how to build the exact-cover matrix for N-Queens, then run a DLX solver to count solutions for N = 5. Next, we convert a partially filled Sudoku into its exact-cover form, solve it with DLX, and present the completed grid.

In [2]:
import numpy as np

## Exact Cover & DLX
An exact-cover problem asks us to select a subset of rows from a binary matrix so that every column contains exactly one “1.” Knuth’s Algorithm X is a recursive, depth-first search for such a cover, and the Dancing-Links data structure makes each cover/uncover operation a constant-time pointer splice in a four-way circular doubly linked list.

## N-Queens
Every way to place N queens on an N×N board so that no two attack corresponds to selecting N rows in a binary matrix with 4N−2 constraints:

- Row constraints (N)
- Column constraints (N)
- Positive-diagonal (2N−1)
- Negative-diagonal (2N−1)

### Build the Exact-Cover Matrix for N=3 (Example)

In [11]:
n = 5
bruh = [[0 for _ in range(6*n - 2)] for _ in range (n**2 + 1)]

for r in range(n):
    for c in range(n):
        # Calculate the conditions that it will cover
        row_map = r # will be 0->n-1
        col_map = (n) + c # will be n->2n-1
        pos_diag_map = (2*n) + r + c # will be 2n->4n-2
        neg_diag_map = (4*n - 2) + n - c + r # will be 4n-2->6n-3

        # Populate the cover_mat. 1 row for each possible position
        bruh[r*n+c+1][row_map] = 1 
        bruh[r*n+c+1][col_map] = 1 
        bruh[r*n+c+1][pos_diag_map] = 1 
        bruh[r*n+c+1][neg_diag_map] = 1 

for i in range(len(bruh)):
    print(bruh[i])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0

### Solve for N=5

In [15]:
# N-Queens
from DLX import DLX_solver

bruh = DLX_solver("N-Queens", 5, [], None)

bruh.empty_to_exact_cover()
bruh.exact_cover_to_dancing_list()
bruh.AlgoX()

print(f"Number of unique solutions for {n}-Queens: {len(bruh.solutions)}")

Number of unique solutions for 5-Queens: 10


## Sudoku
We treat each candidate placement (row 0–8 (r), col 0–8 (c), value 1–9 (v)) as a row in a 730×324 binary matrix covering:
- Cell occupancy (81 columns)
- Row–digit (81)
- Column–digit (81)
- Box–digit (81)

### 3.1 Convert & Solve

In [13]:
# Sudoku
sudoku = np.array([
                    [0,2,0, 0,0,6, 9,0,0],
                    [0,0,0, 0,5,0, 0,2,0],
                    [6,0,0, 3,0,0, 0,0,0],

                    [9,4,0, 0,0,7, 0,0,0],
                    [0,0,0, 4,0,0, 7,0,0],
                    [0,3,0, 2,0,0, 0,8,0],

                    [0,0,9, 0,4,0, 0,0,0],
                    [3,0,0, 9,0,2, 0,1,7],
                    [0,0,8, 0,0,0, 0,0,2]
    ])

from DLX import DLX_solver

dlx = DLX_solver("Sudoku", None, [], sudoku)
dlx.exact_cover_to_dancing_list()
dlx.AlgoX()

[[4 2 5 8 1 6 9 7 3]
 [8 9 3 7 5 4 6 2 1]
 [6 1 7 3 2 9 5 4 8]
 [9 4 1 6 8 7 2 3 5]
 [5 8 2 4 3 1 7 6 9]
 [7 3 6 2 9 5 1 8 4]
 [2 7 9 1 4 8 3 5 6]
 [3 5 4 9 6 2 8 1 7]
 [1 6 8 5 7 3 4 9 2]]


## Conclusion
By encoding both N-Queens and Sudoku as exact-cover matrices and leveraging a Dancing-Links structure for Algorithm X, we:

- Guaranteed that each constraint is covered exactly once.
- Performed each cover/uncover in O(1) pointer operations.
- Pruned the search dramatically via a “minimum‐remaining‐values” heuristic.

These demos illustrate how DLX turns exponential‐time backtracking into a highly efficient solver for real-world puzzles.