# Exact-Cover via Dancing Links: N-Queens & Sudoku Demos
## Abstract
We explore Knuth’s Algorithm X using a toroidal Dancing-Links (DLX) implementation to solve two canonical exact-cover problems: the N-Queens puzzle and Sudoku. First, we show how to build the exact-cover matrix for N-Queens, then run a DLX solver to count solutions for N = 5. Next, we convert a partially filled Sudoku into its exact-cover form, solve it with DLX, and present the completed grid.

In [1]:
import numpy as np

## Exact Cover & DLX
An exact-cover problem asks us to select a subset of rows from a binary matrix so that every column contains exactly one “1.” Knuth’s Algorithm X is a recursive, depth-first search for such a cover, and the Dancing-Links data structure makes each cover/uncover operation a constant-time pointer splice in a four-way circular doubly linked list.

## N-Queens
Every way to place N queens on an N×N board so that no two attack corresponds to selecting N rows in a binary matrix with 4N−2 constraints:

- Row constraints (N)
- Column constraints (N)
- Positive-diagonal (2N−1)
- Negative-diagonal (2N−1)

### Build the Exact-Cover Matrix for N=3 (Example)

In [2]:
n = 5
bruh = [[0 for _ in range(6*n - 2)] for _ in range (n**2 + 1)]

for r in range(n):
    for c in range(n):
        # Calculate the conditions that it will cover
        row_map = r # will be 0->n-1
        col_map = (n) + c # will be n->2n-1
        pos_diag_map = (2*n) + r + c # will be 2n->4n-2
        neg_diag_map = (4*n - 2) + n - c + r # will be 4n-2->6n-3

        # Populate the cover_mat. 1 row for each possible position
        bruh[r*n+c+1][row_map] = 1 
        bruh[r*n+c+1][col_map] = 1 
        bruh[r*n+c+1][pos_diag_map] = 1 
        bruh[r*n+c+1][neg_diag_map] = 1 

for i in range(len(bruh)):
    print(bruh[i])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0

### Solve for N=5

In [3]:
# N-Queens
from DLX import DLX_solver

bruh = DLX_solver("N-Queens", 5, [], None)

bruh.empty_to_exact_cover()
bruh.exact_cover_to_dancing_list()
bruh.AlgoX()

print(f"Number of unique solutions for {n}-Queens: {len(bruh.solutions)}")

Number of unique solutions for 5-Queens: 10


## Sudoku
We treat each candidate placement (row 0–8 (r), col 0–8 (c), value 1–9 (v)) as a row in a 730×324 binary matrix covering:
- Cell occupancy (81 columns)
- Row–digit (81)
- Column–digit (81)
- Box–digit (81)

### 3.1 Convert & Solve

In [4]:
# Sudoku
sudoku = np.array([
                    [0,2,0, 0,0,6, 9,0,0],
                    [0,0,0, 0,5,0, 0,2,0],
                    [6,0,0, 3,0,0, 0,0,0],

                    [9,4,0, 0,0,7, 0,0,0],
                    [0,0,0, 4,0,0, 7,0,0],
                    [0,3,0, 2,0,0, 0,8,0],

                    [0,0,9, 0,4,0, 0,0,0],
                    [3,0,0, 9,0,2, 0,1,7],
                    [0,0,8, 0,0,0, 0,0,2]
    ])

from DLX import DLX_solver

dlx = DLX_solver("Sudoku", None, [], sudoku)
dlx.exact_cover_to_dancing_list()
dlx.AlgoX()

[[4 2 5 8 1 6 9 7 3]
 [8 9 3 7 5 4 6 2 1]
 [6 1 7 3 2 9 5 4 8]
 [9 4 1 6 8 7 2 3 5]
 [5 8 2 4 3 1 7 6 9]
 [7 3 6 2 9 5 1 8 4]
 [2 7 9 1 4 8 3 5 6]
 [3 5 4 9 6 2 8 1 7]
 [1 6 8 5 7 3 4 9 2]]


## Conclusion
By encoding both N-Queens and Sudoku as exact-cover matrices and leveraging a Dancing-Links implementation for Algorithm X, we:

- Guaranteed that each constraint is covered exactly once.
- Performed each cover/uncover in O(1) pointer operations.
- Pruned the search dramatically via a “minimum‐remaining‐values” heuristic.

These demos illustrate how DLX turns exponential‐time backtracking into a highly efficient solver for real-world puzzles.

## Web Interface

Knuth noted in his 2018 lecture on Dancing Links that he had been awaiting an app that visualizes the animations of the links. We did exactly that! On our [GitHub pages](https://eddydpan.github.io/dancing-links/), you can try out the Dancing Links visualizer tool we created by porting the algorithm over to Javascript and creating a front-end with React. If you'd like to see the code for the front-end, feel free to `git switch gh-pages` and poke around in the `src/` directory.

## Testing our Sudoku and N-Queens Solvers

<u>A note on unit testing:</u>

Dan Park, Lily Jiang, and Jess Brown checked off on the way that we implemented our testing. Since our solvers have many representations that are hard to validate (i.e. all points where the solver is leveraging the toroidal doubly linked list), the above course teachers said it was okay for us to simply test if the solvers were working as intended as a whole. Therefore, all testing is done on the results of the overall solvers for sudoku and n-queens for a variety of given inputs.

### Testing Sudoku

In [1]:
%run LeetCode/test_sudoku_solver.py

......
----------------------------------------------------------------------
Ran 6 tests in 0.034s

OK


### Testing N-Queens

In [2]:
%run LeetCode/test_n_queens_solver.py

......
----------------------------------------------------------------------
Ran 6 tests in 0.003s

OK


## LeetCode Problems:

The LeetCode problems that we chose to solve with DLX were:
* 37: Sudoku Solver
* 51: N-Queens
* 52: N-Queens II

You can find our solutions to these problems in the "LeetCode" directory. There, 
each file corresponds to the LeetCode problem with the same name, as follows:
* 37: Sudoku Solver -> LeetCode/sudoku_solver.py
* 51: N-Queens      -> LeetCode/n_queens.py
* 52: N-Queens II   -> LeetCode/n_queens_ii.py

All of these solutions pass the built in unit tests on the LeetCode website. In
order to run the N-Queens solutions on the LeetCode website, simply copy and
paste all of the code in the associated file into the code editor in LeetCode.
As for the Sudoku Solver, you can do the same, just stop your copy at the end at
the comment line "STOP COPY HERE, LEETCODE SOLUTION STOPS HERE STOP", or just 
before the "TEST_INPUT" line.